### ISSUE TITLE
not working on test files

### ISSUE THREAD

**Issue by CharlesIrvineKC** [aaronjensen/flycheck-dogma#2]
flychecking isn't happening automatically on my test files. 
when I run "mix dogma" from the command line, test files are checked

**Comment by aaronjensen** [comment]
flycheck-dogma is now built in to flycheck. I'd recommend uninstalling this package and using the built-in one. If you need help, try https://github.com/flycheck/flycheck

**Comment by CharlesIrvineKC** [comment]
Thanks for the tip. Sadly, I get the same behavior with the built in checker, i.e. no checking in my test files. Do you get otherwise?

Thanks

**Comment by CharlesIrvineKC** [comment]
Well, after some random effort to clean things out and try some things from scratch, I’m getting the proper behavior now in both lib and test files.

Thanks again for the tip.

**Comment by aaronjensen** [comment]
Glad to hear it!
